name: Codium Server action test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set hostname in GITHUB_ENV
        run: echo "HOSTNAME=$(hostname)" >> $GITHUB_ENV

      - name: Tailscale
        uses: gbraad-actions/tailscale-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          args: --ssh --accept-dns=false --operator=runner
          hostname: ${{ env.HOSTNAME }}

      - name: Force failure
        run: |
          echo "::error::This is a forced error message"
          exit 1

      - name: Setup Codium Server
        if: ${{ failure() }}
        uses: ./
        continue-on-error: true
